import { nanoid } from 'nanoid';

export const headerListAmbs = [
  { value: 'ФИО', id: nanoid() },
  { value: 'Программа обучения', id: nanoid() },
  { value: 'Статус', id: nanoid() },
  { value: 'Промокод', id: nanoid() },
  { value: 'Телеграмм', id: nanoid() },
  { value: 'Дата добавления', id: nanoid() },
  { value: 'Электронная почта', id: nanoid() },
  { value: 'Номер телефона', id: nanoid() },
  { value: 'Способ связи', id: nanoid() },
  { value: 'Страна', id: nanoid() },
  { value: 'Город', id: nanoid() },
  { value: 'Образование', id: nanoid() },
  { value: 'Место работы и должность', id: nanoid() },
  { value: 'Цель обучения', id: nanoid() },
  { value: 'Что хочет делать?', id: nanoid() },
  { value: 'Ссылка на блог', id: nanoid() },
  { value: 'Размер одежды', id: nanoid() },
  { value: 'Размер ноги', id: nanoid() },
];

export const settings = [
  { value: 'ФИО', id: nanoid() },
  { value: 'Программа обучения', id: nanoid() },
  { value: 'Статус', id: nanoid() },
  { value: 'Промокод', id: nanoid() },
  { value: 'Телеграмм', id: nanoid() },
  { value: 'Дата добавления', id: nanoid() },
  { value: 'Номер телефона', id: nanoid() },
  { value: 'Способ связи', id: nanoid() },
  { value: 'Страна', id: nanoid() },
  { value: 'Город', id: nanoid() },
  { value: 'Образование', id: nanoid() },
  { value: 'Место работы и должность', id: nanoid() },
  { value: 'Цель обучения', id: nanoid() },
  { value: 'Что хочет делать?', id: nanoid() },
  { value: 'Ссылка на блог', id: nanoid() },
  { value: 'Размер одежды', id: nanoid() },
  { value: 'Размер ноги', id: nanoid() },
];

export const ambNames = [
  { value: 'Петров Сергей Дмитриевич', id: nanoid() },
  { value: 'Кузнецов Владимир Сергеевич', id: nanoid() },
  { value: 'Попов Петр Алексеевич', id: nanoid() },
  { value: 'Петров Алексей Максимович', id: nanoid() },
  { value: 'Михайлов Владимир Артемович', id: nanoid() },
  { value: 'Федоров Владимир Петрович', id: nanoid() },
  { value: 'Федоров Максим Сергеевич', id: nanoid() },
  { value: 'Михайлов Петр Владимирович', id: nanoid() },
  { value: 'Смирнов Андрей Дмитриевич', id: nanoid() },
  { value: 'Кузнецов Владимир Иванович', id: nanoid() },
  { value: 'Соколов Николай Артемович', id: nanoid() },
  { value: 'Михайлов Петр Владимирович', id: nanoid() },
  { value: 'Иванов Андрей Алексеевич', id: nanoid() },
  { value: 'Новиков Дмитрий Максимович', id: nanoid() },
  { value: 'Петров Алексей Владимирович', id: nanoid() },
  { value: 'Иванов Андрей Николаевич', id: nanoid() },
  { value: 'Смирнов Николай Алексеевич', id: nanoid() },
  { value: 'Васильев Максим Николаевич', id: nanoid() },
  { value: 'Новиков Дмитрий Максимович', id: nanoid() },
  { value: 'Федоров Петр Максимович', id: nanoid() },
  { value: 'Петров Николай Иванович', id: nanoid() },
  { value: 'Соколов Петр Петрович', id: nanoid() },
  { value: 'Михайлов Артем Владимирович', id: nanoid() },
  { value: 'Васильев Сергей Петрович', id: nanoid() },
  { value: 'Иванов Артем Артемович', id: nanoid() },
  { value: 'Иванов Петр Андреевич', id: nanoid() },
  { value: 'Федоров Иван Андреевич', id: nanoid() },
  { value: 'Новиков Сергей Иванович', id: nanoid() },
  { value: 'Иванов Иван Петрович', id: nanoid() },
  { value: 'Кузнецов Петр Дмитриевич', id: nanoid() },
  { value: 'Кузнецов Максим Сергеевич', id: nanoid() },
  { value: 'Кузнецов Дмитрий Владимирович', id: nanoid() },
  { value: 'Попов Петр Артемович', id: nanoid() },
  { value: 'Федоров Иван Максимович', id: nanoid() },
  { value: 'Федоров Сергей Алексеевич', id: nanoid() },
  { value: 'Попов Андрей Петрович', id: nanoid() },
  { value: 'Смирнов Алексей Дмитриевич', id: nanoid() },
  { value: 'Федоров Николай Алексеевич', id: nanoid() },
  { value: 'Федоров Петр Артемович', id: nanoid() },
  { value: 'Попов Артем Алексеевич', id: nanoid() },
  { value: 'Михайлов Петр Максимович', id: nanoid() },
  { value: 'Соколов Иван Николаевич', id: nanoid() },
  { value: 'Попов Петр Алексеевич', id: nanoid() },
  { value: 'Кузнецов Николай Иванович', id: nanoid() },
  { value: 'Михайлов Петр Алексеевич', id: nanoid() },
  { value: 'Васильев Николай Андреевич', id: nanoid() },
  { value: 'Попов Петр Максимович', id: nanoid() },
  { value: 'Михайлов Максим Артемович', id: nanoid() },
  { value: 'Кузнецов Максим Артемович', id: nanoid() },
  { value: 'Петров Николай Алексеевич', id: nanoid() },
  { value: 'Попов Артем Петрович', id: nanoid() },
  { value: 'Кузнецов Андрей Сергеевич', id: nanoid() },
  { value: 'Соколов Петр Андреевич', id: nanoid() },
  { value: 'Новиков Сергей Николаевич', id: nanoid() },
  { value: 'Новиков Владимир Дмитриевич', id: nanoid() },
  { value: 'Попов Иван Алексеевич', id: nanoid() },
  { value: 'Смирнов Николай Владимирович', id: nanoid() },
  { value: 'Соколов Андрей Иванович', id: nanoid() },
  { value: 'Федоров Андрей Дмитриевич', id: nanoid() },
  { value: 'Федоров Николай Андреевич', id: nanoid() },
  { value: 'Иванов Андрей Артемович', id: nanoid() },
  { value: 'Попов Алексей Андреевич', id: nanoid() },
  { value: 'Михайлов Петр Андреевич', id: nanoid() },
  { value: 'Попов Петр Иванович', id: nanoid() },
  { value: 'Кузнецов Максим Дмитриевич', id: nanoid() },
  { value: 'Кузнецов Иван Андреевич', id: nanoid() },
  { value: 'Кузнецов Сергей Иванович', id: nanoid() },
  { value: 'Смирнов Алексей Максимович', id: nanoid() },
  { value: 'Петров Владимир Сергеевич', id: nanoid() },
  { value: 'Иванов Иван Николаевич', id: nanoid() },
  { value: 'Михайлов Сергей Сергеевич', id: nanoid() },
  { value: 'Васильев Артем Николаевич', id: nanoid() },
  { value: 'Иванов Петр Иванович', id: nanoid() },
  { value: 'Соколов Петр Артемович', id: nanoid() },
  { value: 'Попов Алексей Иванович', id: nanoid() },
  { value: 'Иванов Алексей Владимирович', id: nanoid() },
  { value: 'Соколов Иван Иванович', id: nanoid() },
  { value: 'Михайлов Сергей Артемович', id: nanoid() },
  { value: 'Васильев Сергей Дмитриевич', id: nanoid() },
  { value: 'Попов Петр Николаевич', id: nanoid() },
  { value: 'Новиков Николай Дмитриевич', id: nanoid() },
  { value: 'Иванов Петр Максимович', id: nanoid() },
  { value: 'Соколов Николай Андреевич', id: nanoid() },
  { value: 'Михайлов Алексей Артемович', id: nanoid() },
  { value: 'Новиков Петр Сергеевич', id: nanoid() },
  { value: 'Федоров Иван Владимирович', id: nanoid() },
  { value: 'Новиков Дмитрий Николаевич', id: nanoid() },
  { value: 'Васильев Николай Петрович', id: nanoid() },
  { value: 'Попов Иван Николаевич', id: nanoid() },
  { value: 'Новиков Сергей Владимирович', id: nanoid() },
  { value: 'Васильев Андрей Максимович', id: nanoid() },
  { value: 'Федоров Николай Сергеевич', id: nanoid() },
  { value: 'Новиков Сергей Алексеевич', id: nanoid() },
  { value: 'Михайлов Николай Артемович', id: nanoid() },
  { value: 'Смирнов Сергей Сергеевич', id: nanoid() },
  { value: 'Федоров Дмитрий Алексеевич', id: nanoid() },
  { value: 'Петров Максим Николаевич', id: nanoid() },
  { value: 'Федоров Иван Николаевич', id: nanoid() },
  { value: 'Новиков Андрей Николаевич', id: nanoid() },
  { value: 'Новиков Петр Петрович', id: nanoid() },
  { value: 'Иванов Алексей Андреевич', id: nanoid() },
  { value: 'Михайлов Сергей Иванович', id: nanoid() },
  { value: 'Смирнов Алексей Алексеевич', id: nanoid() },
  { value: 'Федоров Алексей Артемович', id: nanoid() },
  { value: 'Иванов Артем Максимович', id: nanoid() },
  { value: 'Петров Иван Андреевич', id: nanoid() },
  { value: 'Иванов Петр Петрович', id: nanoid() },
  { value: 'Петров Иван Николаевич', id: nanoid() },
  { value: 'Михайлов Владимир Владимирович', id: nanoid() },
  { value: 'Новиков Петр Дмитриевич', id: nanoid() },
  { value: 'Федоров Алексей Артемович', id: nanoid() },
  { value: 'Новиков Максим Владимирович', id: nanoid() },
  { value: 'Кузнецов Артем Петрович', id: nanoid() },
  { value: 'Соколов Андрей Сергеевич', id: nanoid() },
  { value: 'Васильев Максим Петрович', id: nanoid() },
  { value: 'Петров Максим Андреевич', id: nanoid() },
  { value: 'Смирнов Иван Артемович', id: nanoid() },
  { value: 'Иванов Петр Николаевич', id: nanoid() },
  { value: 'Петров Андрей Андреевич', id: nanoid() },
  { value: 'Попов Николай Дмитриевич', id: nanoid() },
  { value: 'Новиков Алексей Петрович', id: nanoid() },
  { value: 'Иванов Владимир Андреевич', id: nanoid() },
  { value: 'Васильев Дмитрий Иванович', id: nanoid() },
  { value: 'Васильев Алексей Владимирович', id: nanoid() },
  { value: 'Соколов Максим Николаевич', id: nanoid() },
  { value: 'Михайлов Артем Сергеевич', id: nanoid() },
  { value: 'Федоров Андрей Максимович', id: nanoid() },
  { value: 'Попов Николай Андреевич', id: nanoid() },
  { value: 'Кузнецов Иван Иванович', id: nanoid() },
  { value: 'Петров Алексей Максимович', id: nanoid() },
  { value: 'Кузнецов Николай Петрович', id: nanoid() },
  { value: 'Новиков Алексей Алексеевич', id: nanoid() },
  { value: 'Петров Артем Николаевич', id: nanoid() },
  { value: 'Иванов Дмитрий Артемович', id: nanoid() },
  { value: 'Попов Артем Иванович', id: nanoid() },
  { value: 'Соколов Андрей Артемович', id: nanoid() },
  { value: 'Попов Максим Андреевич', id: nanoid() },
  { value: 'Кузнецов Петр Андреевич', id: nanoid() },
  { value: 'Кузнецов Сергей Андреевич', id: nanoid() },
  { value: 'Кузнецов Николай Алексеевич', id: nanoid() },
  { value: 'Михайлов Алексей Владимирович', id: nanoid() },
  { value: 'Кузнецов Владимир Николаевич', id: nanoid() },
  { value: 'Михайлов Артем Петрович', id: nanoid() },
  { value: 'Петров Максим Максимович', id: nanoid() },
  { value: 'Кузнецов Петр Петрович', id: nanoid() },
  { value: 'Иванов Дмитрий Петрович', id: nanoid() },
  { value: 'Соколов Артем Сергеевич', id: nanoid() },
  { value: 'Кузнецов Дмитрий Алексеевич', id: nanoid() },
  { value: 'Соколов Артем Алексеевич', id: nanoid() },
  { value: 'Михайлов Иван Сергеевич', id: nanoid() },
];

export const ambassadorData = [
  // Предыдущие две записи
  {
    id: nanoid(),
    fullName: 'Алексей Иванович Смирнов',
    trainingProgram: 'Frontend-разработка',
    status: 'Активен',
    promoCode: 'FRONT2024',
    telegram: '@AlexSmirnov',
    dateAdded: '2024-01-15',
    email: 'alexey.smirnov@example.com',
    phoneNumber: '+79261234567',
    contactMethod: 'Email',
    country: 'Россия',
    city: 'Москва',
    education: 'Высшее',
    workplaceAndPosition: 'ООО "Разрабы", Frontend-разработчик',
    learningGoal: 'Расширение профессиональных навыков',
    plans: 'Работа над крупным проектом',
    blogLink: 'https://alexsmirnovblog.com',
    clothingSize: 'M',
    shoeSize: 44,
  },
  {
    id: nanoid(),
    fullName: 'Мария Иванова Белова Темнова',
    trainingProgram: 'UI/UX дизайн',
    status: 'Активен',
    promoCode: 'DESIGN2024',
    telegram: '@MariaDesign',
    dateAdded: '2024-02-20',
    email: 'maria.ivanova@example.com',
    phoneNumber: '+79876543210',
    contactMethod: 'Телефон',
    country: 'Россия',
    city: 'Санкт-Петербург',
    education: 'Среднее специальное',
    workplaceAndPosition: 'Фрилансер, UI/UX дизайнер',
    learningGoal: 'Получение новых заказов',
    plans: 'Создание портфолио',
    blogLink: 'https://mariadesignblog.com',
    clothingSize: 'S',
    shoeSize: 38,
  },
  // Добавление дополнительных амбассадоров
].concat(Array.from({ length: 26 }, (_, index) => ({
  id: nanoid(),
  fullName: `Фамилиядлинная Имя Отество ${index + 3}`,
  trainingProgram: ['Frontend-разработка', 'UI/UX дизайн', 'Data Science'][index % 3],
  status: ['Активен', 'Неактивен'][index % 2],
  promoCode: `CODE${index + 3}`,
  telegram: `@User${index + 3}`,
  dateAdded: `2024-0${index % 9 + 1}-0${index % 28 + 1}`,
  email: `user${index + 3}@example.com`,
  phoneNumber: `+7900000000${index + 3}`,
  contactMethod: ['Email', 'Телефон'][index % 2],
  country: 'Россия',
  city: ['Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург'][index % 4],
  education: ['Высшее', 'Среднее специальное'][index % 2],
  workplaceAndPosition: `Компания ${index + 3}, Позиция ${index + 3}`,
  learningGoal: 'Цель обучения',
  plans: 'Планы на будущее',
  blogLink: `https://blog${index + 3}.com`,
  clothingSize: ['S', 'M', 'L'][index % 3],
  shoeSize: 40 + (index % 5),
})));

export default {
  headerListAmbs,
  settings,
  ambassadorData,
  ambNames,
};
